name: jathikaSampatha
id: 321
specialCharactors:
  - image: lagna-abc
    uri: urlToImage

positions:
  - 1: letter
  - 2: number
  - 3: number
  - 4: number
  - 5: number
  - 6: number
  - 7: number

rules:
  - rule: Letter and 6th 6 Numbers Correct
    positions:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    level: 1
    nonFixedPositions:
    positionalValue: true
    nonFixedType:
    matchingCount: 7
    prize: 10000000.00  #10,000,000.00

  - rule: 6 Numbers Correct
    positions:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    level: 2
    positionalValue: true
    matchingCount: 6
    prize: 2000000.00  #2,000,000.00

  - rule: last 5 Numbers Correct
    positions:
      - 3
      - 4
      - 5
      - 6
      - 7
    level: 3
    positionalValue: true
    matchingCount: 5
    prize: 100000.00  #100,000.00

  - rule: last 4 Numbers Correct
    positions:
      - 4
      - 5
      - 6
      - 7
    level: 4
    positionalValue: true
    matchingCount: 4
    prize: 10000.00  #10,000.00

  - rule: First 5 Numbers Correct
    positions:
      - 2
      - 3
      - 4
      - 5
      - 6
    level: 4
    positionalValue: true
    matchingCount: 5
    prize: 10000.00  #10,000.00

  - rule: last 3 Numbers Correct
    positions:
      - 5
      - 6
      - 7
    level: 5
    positionalValue: true
    matchingCount: 3
    prize: 1000.00  #1,000.00

  - rule: First 4 Numbers Correct
    positions:
      - 2
      - 3
      - 4
      - 5
    level: 5
    positionalValue: true
    matchingCount: 4
    prize: 1000.00  #1,000.00

  - rule: 6 numbers correct
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    level: 3
    positionalValue: false
    nonFixedType: number
    matchingCount: 6
    prize: 200.00

  - rule: First 3 Numbers Correct
    positions:
      - 2
      - 3
      - 4
    level: 7
    positionalValue: true
    matchingCount: 3
    prize: 100.00  #50.00

  - rule: last 2 Numbers Correct
    positions:
      - 6
      - 7
    level: 6
    positionalValue: true
    matchingCount: 2
    prize: 50.00  #100.00

  - rule: First 2 Numbers Correct
    positions:
      - 2
      - 3
    level: 7
    positionalValue: true
    matchingCount: 2
    prize: 50.00  #50.00

  - rule: Last Number Correct
    positions:
      - 7
    level: 8
    positionalValue: true
    matchingCount: 1
    prize: 20.00  #20.00

  - rule: Letter Correct
    positions:
      - 1
    level: 8
    positionalValue: true
    matchingCount: 1
    prize: 20.00  #20.00