name: vasanaSampatha
id: 361
specialCharactors:
  - image: lagna-abc
    uri: urlToImage

positions:
  - 1: letter
  - 2: number
  - 3: number
  - 4: number
  - 5: number

rules:
  - rule: Letter and 4 Numbers Correct
    positions:
      - 1
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 1
    positionalValue: false
    matchingCount: 5
    prize:  20727810.90  #10,000,000.00

  - rule: 4 Numbers Correct
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 2
    positionalValue: true
    matchingCount: 4
    prize: 100000.00  #2,000,000.00

  - rule: Letter and any 3 numbers correct
    positions:
      - 1
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 3
    positionalValue: false
    nonFixedType: number
    matchingCount: 4
    prize: 100000.00  #100,000.00

  - rule: Any 3 numbers correct
    positions:
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 4
    positionalValue: false
    nonFixedType: number
    matchingCount: 3
    prize: 2000.00  #10,000.00

  - rule: Letter and any 2 numbers correct
    positions:
      - 1
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 5
    positionalValue: true
    nonFixedType: number
    matchingCount: 3
    prize: 500.00  #1,000.00

  - rule: Any 2 numbers correct
    positions:
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 6
    positionalValue: true
    nonFixedType: number
    matchingCount: 2
    prize: 100.00  #100.00

  - rule: Letter and any number correct
    positions:
      - 1
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 8
    positionalValue: true
    nonFixedType: number
    matchingCount: 2
    prize: 60.00  #20.00


  - rule: Any Number Correct
    positions:
    nonFixedPositions:
      - 2
      - 3
      - 4
      - 5
    level: 4
    positionalValue: true
    nonFixedType: number
    matchingCount: 1
    prize: 20.00  #10,000.00

  - rule: Letter correct
    positions:
      - 1
    level: 5
    positionalValue: true
    matchingCount: 1
    prize: 20.00  #1,000.00
